version: '3.9'

services:
  database:
    image: postgres:15.1-alpine
    ports:
      - 15432:5432
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "security_lab_db"
    container_name: security_lab_db

volumes:
  postgres_vol: {}
